
#Android path of bili
#originalAndroidPath = e:\\ori

#originalVideoPartsPath = e:\\ori

#originalAndroidPath = F:\\tmp\\114812612777552\\
#originalVideoPartsPath = F:\\tmp\\114812612777552\\

originalAndroidPath = F:\\j\\
originalVideoPartsPath = F:\\j\\

#originalAndroidPath = E:\\360Downloads\\bili
#originalAndroidPath = E:\\360Downloads\\biliOri
#target path to save.
targetPath = D:\\software\\mouse\\x360Map.config
