#FolderToHandle=J:\\censored\\SIVR\\
#FolderToHandle=K:\\censored\\SIVR\\
#FolderToHandle=L:\leak\\
#FolderToHandle=F:\\Downloads\\f40\\
#FolderToHandle=E:\\Downloads\\todo1\\
#FolderToHandle=t:\\download\\ou05\\
#FolderToHandle=S:\\Downloads\\JPVR\\
#FolderToHandle=F:\\toMove\\VR\\
#FolderToHandle=F:\\Downloads\\special\\\u4E2D\u5143\u8282\u5FC5\u770B\u7684100\u90E8\u7535\u5F71\uFF08part II\uFF09\u627E\u7247\u5927\u5E08\u4F0A\u4F0A\u4E07\\
#FolderToHandle=P:\\OU2\\POVROriginals\\
#FolderToHandle=F:\\Downloads\\f05\\
#FolderToHandle=P:\\JAV1\\IPVR_to_2\\
#FolderToHandle=E:\\r\\
#FolderToHandle=K:\\censored\\SIVR\\
#FolderToHandle=W:\\a\\
#FolderToHandle=W:\\tmp2Story\\
#FolderToHandle=T:\\forShare2\\movie\\
#FolderToHandle=W:\\porn_story\\
#FolderToHandle=W:\\a\\
#FolderToHandle=P:\\JAV1\\CAFR_to5\\
#FolderToHandle=d:\\POVROriginals\\
#FolderToHandle=F:\\r\\
#FolderToHandle=F:\\PS3Tmp\\
#FolderToHandle=f:\\Downloads\\OU08\\
#FolderToHandle=F:\\JPVR\\
#FolderToHandle=F:\\Downloads\\\aoa\\portrait\\
#FolderToHandle=Y:\\VR\\hologirlsvr.com Gear VR\\
#FolderToHandle=E:\\a\\
#FolderToHandle=E:\\Downloads\\receiveC\\

#FolderToHandle=E:\\p\\
#FolderToHandle=F:\\Downloads\\china\\
#FolderToHandle=P:\\OU3\\CzechVRFetish\\
#FolderToHandle=W:\\tokyoHot\\
#FolderToHandle=E:\\r\\
#FolderToHandle=D:\\Downloads\\KylerQuinn\\
#FolderToHandle=F:\\Downloads\\ou07\\
#FolderToHandle=F:\\ou3\\
#FolderToHandle=F:\\toMove\\VR\\
#FolderToHandle=F:\\cao\\
#FolderToHandle=F:\\toMove\\VR\\
#FolderToHandle=F:\\r\\
#FolderToHandle=P:\\2DMovie\\
#FolderToHandle=P:\\censor_removed\\
#FolderToHandle=P:\\marica-hase\\
#FolderToHandle=G:\\old_moved_to_JavG\\
#FolderToHandle=D:\\Downloads\\hd800_20241203\\unzip\\
#FolderToHandle=t:\\Downloads\\hd800_20260131\\unzip\\
#FolderToHandle=T:\\download\\ou08\\
#FolderToHandle=I:\\OU3\\NaughtyAmerica\\
#FolderToHandle=g:\\
#FolderToHandle=D:\\\x1\\
#FolderToHandle=S:\\x5\\
#FolderToHandle=F:\\Downloads\\ar01\\
#FolderToHandle=H:\\tmp\\
#FolderToHandle=T:\\download\\\ou08\\
#FolderToHandle=T:\\toMove\\VR\\
#FolderToHandle=d:\\x2\\
FolderToHandle=E:\\JAV4KG\\group\\model\\

#FolderToHandle=T:\\VR\\
#FolderToHandle=T:\\p\\
#FolderToHandle=F:\\animeSong\\
#FolderToHandle=V:\\jav5\\Downloads\\ou7\\
#FolderToHandle=X:\\Downloads\\facialab\\
#FolderToHandle=T:\\Downloads\\hd800_20251221\\unzip\\


#FolderToHandle=x:\\toMove\\x5\\
#FolderToHandle=s:\\toMove\\s1\\
#FolderToHandle=F:\\x2\\
#FolderToHandle=f:\\p\\
#FolderToHandle=x:\\x2\\
#FolderToHandle=X:\\Downloads\\gaggers\\
#FolderToHandle=f:\\x1\\,x:\\x1\\,s:\\x1\\
#FolderToHandle=T:\\toMove\\VR\\SLROriginals\\,P:\\OU1\\SLROriginals\\
#FolderToHandle=T:\\toMove\\t1\\
#FolderToHandle=T:\\VR\\BaDoinkVR\\,P:\\OU3\\BaDoinkVR\\
#FolderToHandle=F:\\toMove\\VR\\LustReality\\,P:\OU1\LustReality\\
#FolderToHandle=T:\\VR\\CzechVR\\,P:\\OU3\\CzechVR\\
#FolderToHandle=D:\\89\\oculusTV\\
#FolderToHandle=F:\\toMove\\VR\\#FolderToHandle=T:\\download\\ou\\
#FolderToHandle=t:\\r\\
#FolderToHandle=t:\\p\\
#FolderToHandle=T:\\download\\t2\\
#FolderToHandle=T:\\toMove\\2dPorn\\
#FolderToHandle=t:\\tmp\\,F:\\toMove\\2dPorn\\

isPrintOnly=true1
isRenamePicByParent=true
# 0: disabled
# 1: by parent
# 2: by parent when filename doesn't contains Chinese/JP
# 3: by parent smartly. Will only rename by parent when filename contains '...' and 'vac'.
# 4: by parent forcely
isRenameByParent=4
# force to prepend/append, instead of overwrite
isRenameByParent_force=true1
# true for prepend, false for append
isRenameByParent_prepend=true1
isRenameByVideo=true
isRemoveDupSuffix=true
isRemoveNumbericPic=false
isSkipPic=true
dupSizeThrottleInKB=4096
videoAdSizeLimitInMB=50
bigVideoSizeFloorInMB=50
isRemoveAdsStr=true
isUppercaseVideoId=true
isAppendResolution=true1
appendResultionIfFirstNumberGreaterThan=0
isAppendDuration=true1
isRemoveSameSizefile=true1
isRemoveSameFileLowResfile=true
isRemoveSameDurationfile=true1
#removeLowResolutionVideoFirstNumber=1920
removeLowResolutionVideoFirstNumber=0
dupDurationThrottleInSec=1
